remote_theme: vanjac/theme
defaults:
  -
    scope:
      path: ""
    values:
      links:
        -
          title: Google Play
          url: https://play.google.com/store/apps/details?id=com.vantjac.voxel
        -
          title: GitHub
          url: https://github.com/vanjac/voxel-editor
